---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: es-vs-2
  namespace: cluster-2
spec:
  hosts:
  - "es-2.${domain}"
  gateways:
  - gw-2
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: es-2-es-http.cluster-2.svc.cluster.local
        port:
          number: 9200