---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: es-vs-1
  namespace: cluster-1
spec:
  hosts:
  - "es-1.${domain}"
  gateways:
  - gw-1
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: es-1-es-http.cluster-1.svc.cluster.local
        port:
          number: 9200