---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kb-vs-1
  namespace: cluster-1
spec:
  hosts:
  - "kb-1.${domain}"
  gateways:
  - gw-1
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: kb-1-kb-http.cluster-1.svc.cluster.local
        port:
          number: 5601